/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecretariatRouteImport } from './routes/secretariat'
import { Route as ReportsPatientIdRouteImport } from './routes/reports.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretariatRoute = SecretariatRouteImport.update({
  id: '/secretariat',
  path: '/secretariat',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPatientIdRoute = ReportsPatientIdRouteImport.update({
  id: '/reports/$patientId',
  path: '/reports/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/secretariat': typeof SecretariatRoute
  '/reports/$patientId': typeof ReportsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/secretariat': typeof SecretariatRoute
  '/reports/$patientId': typeof ReportsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/secretariat': typeof SecretariatRoute
  '/reports/$patientId': typeof ReportsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/secretariat' | '/reports/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/secretariat' | '/reports/$patientId'
  id: '__root__' | '/' | '/secretariat' | '/reports/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SecretariatRoute: typeof SecretariatRoute
  ReportsPatientIdRoute: typeof ReportsPatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretariat': {
      id: '/secretariat'
      path: '/secretariat'
      fullPath: '/secretariat'
      preLoaderRoute: typeof SecretariatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$patientId': {
      id: '/reports/$patientId'
      path: '/reports/$patientId'
      fullPath: '/reports/$patientId'
      preLoaderRoute: typeof ReportsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SecretariatRoute: SecretariatRoute,
  ReportsPatientIdRoute: ReportsPatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
