/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SecretariatRouteImport } from './routes/secretariat'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsPatientIdRouteImport } from './routes/reports.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretariatRoute = SecretariatRouteImport.update({
  id: '/secretariat',
  path: '/secretariat',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsPatientIdRoute = ReportsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => ReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parametres': typeof ParametresRoute
  '/reports': typeof ReportsRouteWithChildren
  '/secretariat': typeof SecretariatRoute
  '/reports/$patientId': typeof ReportsPatientIdRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parametres': typeof ParametresRoute
  '/secretariat': typeof SecretariatRoute
  '/reports/$patientId': typeof ReportsPatientIdRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parametres': typeof ParametresRoute
  '/reports': typeof ReportsRouteWithChildren
  '/secretariat': typeof SecretariatRoute
  '/reports/$patientId': typeof ReportsPatientIdRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parametres'
    | '/reports'
    | '/secretariat'
    | '/reports/$patientId'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/parametres' | '/secretariat' | '/reports/$patientId' | '/reports'
  id:
    | '__root__'
    | '/'
    | '/parametres'
    | '/reports'
    | '/secretariat'
    | '/reports/$patientId'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParametresRoute: typeof ParametresRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SecretariatRoute: typeof SecretariatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretariat': {
      id: '/secretariat'
      path: '/secretariat'
      fullPath: '/secretariat'
      preLoaderRoute: typeof SecretariatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/$patientId': {
      id: '/reports/$patientId'
      path: '/$patientId'
      fullPath: '/reports/$patientId'
      preLoaderRoute: typeof ReportsPatientIdRouteImport
      parentRoute: typeof ReportsRoute
    }
  }
}

interface ReportsRouteChildren {
  ReportsPatientIdRoute: typeof ReportsPatientIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsPatientIdRoute: ReportsPatientIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParametresRoute: ParametresRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SecretariatRoute: SecretariatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
